source 'https://rubygems.org'

gem 'rails', '3.2.22.5'
gem 'json'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'mysql2', '~> 0.3.21'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.6'
  gem 'coffee-rails', '~> 3.2.2'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier'#, '>= 1.0.3'
end

#gem 'jquery-rails'
gem 'prototype-rails', '~> 3.2.1'
gem 'prototype_legacy_helper', '0.0.0', :git => 'git://github.com/rails/prototype_legacy_helper.git' # Esto es para mantener soporte de form_remote_tag en Rails3
# Gemas para hacer mas bonitos los select (funciona con prototype y jquery)
gem 'ajax-chosen-rails'
gem 'chosen-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Deploy with Capistrano
# gem 'capistrano'

# Traducciones
gem 'gettext_i18n_rails'
gem 'fast_gettext'
gem 'rails-i18n', '~> 3'
gem 'i18n'

# Solo para el entorno de desarrollo
group :development do
  # Para buscar traducciones
  gem 'gettext'#, '>=1.9.3', :require => false
  # Para debug
  gem 'byebug'
  # Para generar UML
  #gem "rails-erd"
  # Para hacer volcados de BBDD en un seeds
  gem "seed_dump"
  #gem "seed_dump", "~> 0.4.2"
  # Para usar Unicorn en lugar de WEBrick
  gem "thin"
  gem 'rubysl-pty', platforms: :ruby
  gem 'web-console-rails3', platforms: :ruby
  # Test-unit deja de estar en el core, pero se carga como gema
  gem 'test-unit'

  # Embed the V8 JavaScript interpreter into Ruby
  #gem 'therubyracer'
end

# Otras gemas
#gem "autocomplete" # Da un error al arrancar
#gem "autocomplete", :git => 'git://github.com/voislavj/autocomplete.git'
#gem "auto_complete", :git => 'git://github.com/david-kerins/auto_complete.git'
#gem "respond_to_parent", :git => 'git://github.com/itkin/respond_to_parent.git' # Da error cargando como gema. Cargado como plugin.
gem "spreadsheet"
gem "spreadsheet_on_rails", :git => 'git://github.com/10to1/spreadsheet_on_rails.git'
gem "tinymce-rails", '= 3.5.8.3'
gem 'tinymce-rails-langs', '~> 3'
gem 'tinymce-rails-imageupload', '~> 3.5'
gem "paperclip", "~> 3.5"
gem 'will_paginate', '~> 3.1'
gem 'calendar_date_select', :git => 'git://github.com/paneq/calendar_date_select.git'
gem 'dav4rack'
gem 'shrimp'

# Descarga de documentos de un espacio documental
gem 'rubyzip'

# Generacion de DOCX en base a templates
#gem 'docx_templater'
# (usamos ffmike/docx_builder)
gem 'docx_builder'

# Webservices
# esto hay que solucionarlo para que solo este en el plugin webservices
# sin embargo no funciona la solucion de https://github.com/nesquena/rabl/wiki/Setup-rabl-with-rails-engines
gem 'rabl'
gem 'oj'

# Captcha
gem "galetahub-simple_captcha", :require => "simple_captcha"

# Oauth
gem 'doorkeeper', '1.4.0'

# Solo los cargamos si esta presente en el sistema
puts ENV["GOR_PLUGINS"]
Dir[(ENV["GOR_PLUGINS"]||"/usr/share/gong/plugins") + "/*/*.gemspec"].each do |gemspec_file|
  dir_name = File.dirname(gemspec_file)
  gem_name = File.basename(gemspec_file, File.extname(gemspec_file))

  # Register that engine as a dependency, *without* being required
  #gem gem_name, :path => dir_name, :require => false
  gem gem_name, :path => dir_name
end

gem 'nokogiri'
gem 'execjs'
gem 'rack-cache'

# Convierte numeros a palabras segun los locales elegidos
gem 'numbers_and_words'

# No se porque hay que ponerlo aqui, pero sino se incluye no funciona Rails Engines Load Revisar
gem 'swagger-blocks'

gem 'ffaker'