# Be sure to restart your server when you modify this file.

# These inflection rules are supported but not enabled by default:
# ActiveSupport::Inflector.inflections do |inflect|
#   inflect.acronym 'RESTful'
# end

# Add new inflection rules using the following format 
# (all these examples are active by default):
ActiveSupport::Inflector.inflections do |inflect|
#   inflect.plural /^(ox)$/i, '\1en'
#   inflect.singular /^(ox)en/i, '\1'
#   inflect.irregular 'person', 'people'
#   inflect.uncountable %w( fish sheep )

    inflect.irregular 'proyecto', 'proyecto'
    inflect.irregular 'moneda', 'moneda'
    inflect.irregular 'agente', 'agente'
    inflect.irregular 'libro', 'libro'
    inflect.irregular 'partida', 'partida'
    inflect.irregular 'proyecto', 'proyecto'
    inflect.irregular 'pais', 'pais'
    inflect.irregular 'financiacion', 'financiacion'
    inflect.irregular 'convocatoria', 'convocatoria'
    inflect.irregular 'convocatoria_x_pais', 'convocatoria_x_pais'
    inflect.irregular 'usuario', 'usuario'
    inflect.irregular 'etapa', 'etapa'
    inflect.irregular 'presupuesto', 'presupuesto'
    inflect.irregular 'actividad', 'actividad'
    inflect.irregular 'presupuesto_detallado', 'presupuesto_detallado'
    inflect.irregular 'gasto', 'gasto'
    inflect.irregular 'transferencia', 'transferencia'
    inflect.irregular 'gasto_importar', 'gasto_importar'
    inflect.irregular 'presupuesto_importar', 'presupuesto_importar'
    inflect.irregular 'ingreso', 'ingreso'
    inflect.irregular 'identificacion', 'identificacion'
    inflect.irregular 'datos_basicos', 'datos_basicos'
    inflect.irregular 'poblacion', 'poblacion'
    inflect.irregular 'intervencion', 'intervencion'
    inflect.irregular 'actuacion', 'actuacion'
    inflect.irregular 'documento', 'documento'
    inflect.irregular 'adjunto', 'adjunto'
    inflect.irregular 'comentario', 'comentario'
    inflect.irregular 'resultado', 'resultado'
    inflect.irregular 'actividad', 'actividad'
    inflect.irregular 'actividad_detallada', 'actividad_detallada'
    inflect.irregular 'subactividad_detallada', 'subactividad_detallada'
    inflect.irregular 'objetivo', 'objetivo'
    inflect.irregular 'especifico', 'especifico'
    inflect.irregular 'sector', 'sector'
    inflect.irregular 'area', 'area'
    inflect.irregular 'estado', 'estado'
    inflect.irregular 'definicion_estado', 'definicion_estado'
    inflect.irregular 'tarea', 'tarea'
    inflect.irregular 'tipo', 'tipo'
    inflect.irregular 'indicador', 'indicador'
    inflect.irregular 'fuente_verificacion', 'fuente_verificacion'
    inflect.irregular 'provincia', 'provincia'
    inflect.irregular 'comunidad', 'comunidad'
    inflect.irregular 'municipio', 'municipio'
    inflect.irregular 'etiqueta', 'etiqueta'
    inflect.irregular 'empleado', 'empleado'
    inflect.irregular 'hipotesis', 'hipotesis'
    inflect.irregular 'estado_tarea', 'estado_tarea'
    inflect.irregular 'area_geografica', 'area_geografica'
    inflect.irregular 'proyecto_x_financiador', 'proyecto_x_financiador'
    inflect.irregular 'implementador', 'implementador'
    inflect.irregular 'proyecto_x_implementador', 'proyecto_x_implementador'
    inflect.irregular 'financiador', 'financiador'
    inflect.irregular 'definicion_dato', 'definicion_dato'
    inflect.irregular 'dato_integro', 'dato_integro'
    inflect.irregular 'dato_cadena', 'dato_cadena'
    inflect.irregular 'dato_texto', 'dato_texto'
    inflect.irregular 'pago', 'pago'
    inflect.irregular 'variable_indicador', 'variable_indicador'
    inflect.irregular 'valor_variable_indicador', 'valor_variable_indicador'
    inflect.irregular 'marcado', 'marcado'
    inflect.irregular 'v_presupuesto_agente_detallado', 'v_presupuesto_agente_detallado'
    inflect.irregular 'espacio', 'espacio'
    inflect.irregular 'tasa_cambio', 'tasa_cambio'
    inflect.irregular 'tasa_cambio_x_etapa', 'tasa_cambio_x_etapa'
    inflect.irregular 'subtipo_movimiento', 'subtipo_movimiento'
    inflect.irregular 'transferencia_x_agente', 'transferencia_x_agente'
    inflect.irregular 'datos_tarjeta_socio', 'datos_tarjeta_socio'
    inflect.irregular 'valor_intermedio_x_actividad', 'valor_intermedio_x_actividad'
    inflect.irregular 'valor_intermedio_x_subactividad', 'valor_intermedio_x_subactividad'
    inflect.irregular 'valor_intermedio_x_indicador', 'valor_intermedio_x_indicador'
    inflect.irregular 'grupo_dato_dinamico', 'grupo_dato_dinamico'
    inflect.irregular 'etiqueta_tecnica', 'etiqueta_tecnica'
    inflect.irregular 'objetivo_general', 'objetivo_general'
    inflect.irregular 'grupo_usuario', 'grupo_usuario'
    inflect.irregular 'usuario_x_grupo_usuario', 'usuario_x_grupo_usuario'
    inflect.irregular 'cuenta_contable', 'cuenta_contable'
    inflect.irregular 'tipo_periodo', 'tipo_periodo'
    inflect.irregular 'periodo', 'periodo'
    inflect.irregular 'tipo_personal', 'tipo_personal'
    inflect.irregular 'personal', 'personal'
    inflect.irregular 'plugin', 'plugin'
    inflect.irregular 'log_contabilidad', 'log_contabilidad'
    inflect.irregular 'tipo_convocatoria', 'tipo_convocatoria'
    inflect.irregular 'proveedor', 'proveedor'
    inflect.irregular 'tipo_contrato', 'tipo_contrato'
    inflect.irregular 'tipo_contrato_x_documento', 'tipo_contrato_x_documento'
    inflect.irregular 'workflow_contrato', 'workflow_contrato'
    inflect.irregular 'workflow_contrato_x_workflow_contrato', 'workflow_contrato_x_workflow_contrato'
    inflect.irregular 'workflow_contrato_x_etiqueta', 'workflow_contrato_x_etiqueta'
    inflect.irregular 'contrato', 'contrato'
    inflect.irregular 'contrato_x_actividad', 'contrato_x_actividad'
    inflect.irregular 'contrato_x_documento', 'contrato_x_documento'
    inflect.irregular 'contrato_x_financiador', 'contrato_x_financiador'
    inflect.irregular 'periodo_contrato', 'periodo_contrato'
    inflect.irregular 'partida_ingreso', 'partida_ingreso'
    inflect.irregular 'presupuesto_ingreso', 'presupuesto_ingreso'
    inflect.irregular 'presupuesto_ingreso_detallado', 'presupuesto_ingreso_detallado'
    inflect.irregular 'ingreso', 'ingreso'
    inflect.irregular 'rol', 'rol'
    inflect.irregular 'permiso_x_rol', 'permiso_x_rol'
    inflect.irregular 'tipo_agente', 'tipo_agente'
    inflect.irregular 'gor_config', 'gor_config'
    inflect.irregular 'programa_marco', 'programa_marco'
    inflect.irregular 'log_exportacion', 'log_exportacion'
    inflect.irregular 'indicador_general', 'indicador_general'
    inflect.irregular 'indicador_general_x_programa_marco', 'indicador_general_x_programa_marco'
    inflect.irregular 'indicador_general_x_proyecto', 'indicador_general_x_proyecto'
    inflect.irregular 'valor_x_indicador_general', 'valor_x_indicador_general'
    inflect.irregular 'empleado_salario_hora', 'empleado_salario_hora'

    # Para la salida del RABL
    inflect.singular /([rlnd])es([A-Z]|_|$)/, '\1\2'
    inflect.irregular 'actividad_global', 'actividades_globales'
end
